### ISSUE TITLE
After update HA to 2021.12  xiaomi_viomi: Error on device update!

### ISSUE THREAD

**Issue by Jimmyboy83** [nergal/homeassistant-vacuum-viomi#17]
Hi! Thank you for your integration
There is an issue after HA 2021.12 update
Can you help?
Vacuum is V-RVCLM21B  viomi.vacuum.v6

xiaomi_viomi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_viomi/vacuum.py", line 242, in update
    self._fan_speeds = state.fan_speed_presets()
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 179, in _wrap
    if gco is not None and gco.output is not None:
AttributeError: 'ViomiVacuumStatus' object has no attribute '_model'

**Comment by winnertako** [comment]
Hello @nergal ! Happy New Year!! 

I have the same problem with my Viomi Vaccum v8.

After the HA boot I have this error:

`Unable to prepare setup for platform xiaomi_viomi.vacuum: Platform not found (No module named 'miio.viomivacuum').`

A few minutes later I have the same error than @Jimmyboy83:

`Logger: homeassistant.components.vacuum
Source: custom_components/xiaomi_viomi/vacuum.py:242
Integration: Vacuum (documentation, issues)
First occurred: 8:02:26 PM (1 occurrences)
Last logged: 8:02:26 PM

xiaomi_viomi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_viomi/vacuum.py", line 242, in update
    self._fan_speeds = state.fan_speed_presets()
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 179, in _wrap
    if gco is not None and gco.output is not None:
AttributeError: 'ViomiVacuumStatus' object has no attribute '_model'
`
Can you help us?

Thank you

**Comment by marceloquito** [comment]
Any update on this? Same problem here

**Comment by nergal** [comment]
I've made a few fixes to support the latest HA build and now it seems to be good. Tested on 2021.12.8.

Would be great if you guys can test it (v0.0.3) and put some feedback here so I can close the ticket.

**Comment by winnertako** [comment]
@nergal all good! Thank you for your attention 💪
